version: "3.8"

services:
  frontend:
    container_name: pal-frontend
    image: pal-frontend
    depends_on:
      - backend
    environment:
      - NODE_ENV=dev
    build:
      context: ./btp-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./btp-frontend:/code
      - /code/node_modules
    restart: on-failure

  backend:
    container_name: pal-backend
    image: pal-backend
    depends_on:
      - mongodb
    build:
      context: ./backend
    environment:
      - NODE_ENV=DEV
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./backend:/code
      - /code/node_modules

  scripts:
    container_name: pal-scripts
    image: pal-scripts
    depends_on:
      - mongodb
    build:
      context: ./scripts
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./scripts:/code
      - /code/node_modules

  mongodb:
    container_name: pal-mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: on-failure
    volumes:
      - pal-mongodb:/data/db

volumes:
  pal-mongodb:
